language: go
go_import_path: golang.org/x/crypto
before_install:
- go get github.com/google/wire
- go get github.com/mattn/goveralls
- go test -v -covermode=count -coverprofile=coverage.out ./...
go:
- 1.x
script:
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
